name: rats
channels: !!python/tuple
- !!python/unicode 'defaults'
dependencies:
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- bzip2=1.0.6=3
- cairo=1.12.18=6
- configparser=3.5.0=py27_0
- curl=7.49.0=1
- decorator=4.0.10=py27_0
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_0
- fontconfig=2.11.1=6
- freetype=2.5.5=1
- functools32=3.2.3.2=py27_0
- get_terminal_size=1.0.0=py27_0
- icu=54.1=0
- ipykernel=4.5.0=py27_0
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- jbig=2.1=0
- jinja2=2.8=py27_1
- jpeg=8d=2
- jsonschema=2.5.1=py27_0
- jupyter_client=4.4.0=py27_0
- jupyter_core=4.2.0=py27_0
- libffi=3.2.1=0
- libpng=1.6.22=0
- libsodium=1.0.10=0
- libtiff=4.0.6=2
- libxml2=2.9.2=0
- markupsafe=0.23=py27_2
- mistune=0.7.3=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.1.0=py27_0
- notebook=4.2.3=py27_0
- openssl=1.0.2j=0
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pcre=8.39=0
- pexpect=4.0.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=8.1.2=py27_0
- pixman=0.32.6=0
- prompt_toolkit=1.0.3=py27_0
- ptyprocess=0.5.1=py27_0
- pygments=2.1.3=py27_0
- python=2.7.12=1
- pyzmq=15.4.0=py27_0
- r::glib=2.43.0=2
- r::gsl=1.16=1
- r::harfbuzz=0.9.35=6
- r::libgcc=4.8.5=1
- r::ncurses=5.9=8
- r::pango=1.36.8=3
- r::r=3.3.1=r3.3.1_0
- r::r-assertthat=0.1=r3.3.1_4
- r::r-base=3.3.1=3
- r::r-base64enc=0.1_3=r3.3.1_0
- r::r-bh=1.60.0_2=r3.3.1_0
- r::r-boot=1.3_18=r3.3.1_0
- r::r-cairo=1.5_9=r3.3.1_0
- r::r-class=7.3_14=r3.3.1_0
- r::r-cluster=2.0.4=r3.3.1_0
- r::r-codetools=0.2_14=r3.3.1_0
- r::r-colorspace=1.2_6=r3.3.1_0
- r::r-crayon=1.3.1=r3.3.1_0
- r::r-curl=0.9.7=r3.3.1_0
- r::r-dbi=0.4_1=r3.3.1_0
- r::r-devtools=1.11.1=r3.3.1_0
- r::r-dichromat=2.0_0=r3.3.1_2
- r::r-digest=0.6.9=r3.3.1_0
- r::r-doparallel=1.0.10=r3.3.1_0
- r::r-dplyr=0.4.3=r3.3.1_0
- r::r-evaluate=0.9=r3.3.1_0
- r::r-foreach=1.4.3=r3.3.1_0
- r::r-foreign=0.8_66=r3.3.1_0
- r::r-ggplot2=2.1.0=r3.3.1_0
- r::r-git2r=0.15.0=r3.3.1_0
- r::r-gtable=0.2.0=r3.3.1_0
- r::r-httr=1.2.0=r3.3.1_0
- r::r-irdisplay=0.4.3=r3.3.1_2
- r::r-irkernel=0.7=r3.3.1_2
- r::r-iterators=1.0.8=r3.3.1_0
- r::r-jsonlite=0.9.22=r3.3.1_0
- r::r-kernsmooth=2.23_15=r3.3.1_0
- r::r-labeling=0.3=r3.3.1_2
- r::r-lattice=0.20_33=r3.3.1_0
- r::r-lazyeval=0.2.0=r3.3.1_0
- r::r-magrittr=1.5=r3.3.1_2
- r::r-mass=7.3_45=r3.3.1_0
- r::r-matrix=1.2_6=r3.3.1_0
- r::r-memoise=1.0.0=r3.3.1_0
- r::r-mgcv=1.8_12=r3.3.1_0
- r::r-mime=0.4=r3.3.1_0
- r::r-munsell=0.4.3=r3.3.1_0
- r::r-nlme=3.1_128=r3.3.1_0
- r::r-nnet=7.3_12=r3.3.1_0
- r::r-openssl=0.9.4=r3.3.1_0
- r::r-pbdzmq=0.2_3=r3.3.1_0
- r::r-plyr=1.8.4=r3.3.1_0
- r::r-r6=2.1.2=r3.3.1_0
- r::r-rcolorbrewer=1.1_2=r3.3.1_2
- r::r-rcpp=0.12.5=r3.3.1_0
- r::r-recommended=3.3.1=r3.3.1_0
- r::r-repr=0.7=r3.3.1_0
- r::r-reshape2=1.4.1=r3.3.1_2
- r::r-rpart=4.1_10=r3.3.1_0
- r::r-rstudioapi=0.5=r3.3.1_0
- r::r-scales=0.4.0=r3.3.1_0
- r::r-spatial=7.3_11=r3.3.1_0
- r::r-stringi=1.1.1=r3.3.1_0
- r::r-stringr=1.0.0=r3.3.1_0
- r::r-survival=2.39_4=r3.3.1_0
- r::r-uuid=0.1_2=r3.3.1_0
- r::r-whisker=0.3_2=r3.3.1_2
- r::r-withr=1.0.2=r3.3.1_0
- r::singledispatch=3.4.0.3=py27_1
- readline=6.2=2
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- six=1.10.0=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- terminado=0.6=py27_0
- tk=8.5.18=0
- tornado=4.4.2=py27_0
- traitlets=4.3.1=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- xz=5.2.2=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - ipython-genutils==0.1.0
  - jupyter-client==4.4.0
  - jupyter-core==4.2.0
  - prompt-toolkit==1.0.3
